version: "3.8"

# Including necessary compose files for different services
include:
  - nginx-compose.yaml
  - simple-login-compose.yaml
  - postfix-compose.yaml

# Networks configuration
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

# Define the environment variables here or use .env file
services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN:-app}
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /etc/nginx/conf.d/default.conf ]; then
        sed -e \"s/app.domain.tld/${SUBDOMAIN}.${DOMAIN}/g\" -e \"s/domain.tld/${DOMAIN}/g\" /etc/nginx/conf.d/default-init.conf.tpl > /etc/nginx/conf.d/default.conf;
      fi &&
      exec nginx -g 'daemon off;'"

  postfix:
    build: ./postfix
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN:-app}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /etc/postfix/virtual ]; then
        sed -e \"s/domain.tld/${DOMAIN}/g\" /etc/postfix/conf.d/virtual.tpl > /etc/postfix/conf.d/virtual;
      fi &&
      if [ ! -f /etc/postfix/virtual-regexp ]; then
        sed -e \"s/domain.tld/${DOMAIN}/g\" /etc/postfix/conf.d/virtual-regexp.tpl > /etc/postfix/conf.d/virtual-regexp;
      fi &&
      sed -e \"s/myuser/${POSTGRES_USER}/g\" /etc/postfix/conf.d/pgsql-relay-domains.cf.tpl > /etc/postfix/conf.d/pgsql-relay-domains.cf &&
      sed -i -e \"s/mypassword/$(echo ${POSTGRES_PASSWORD} | sed 's/[][\/\.|$(){}?+*^]/\\\\&/g')/g\" /etc/postfix/conf.d/pgsql-relay-domains.cf &&
      sed -i -e \"s/domain.tld/${DOMAIN}/g\" /etc/postfix/conf.d/pgsql-relay-domains.cf &&
      sed -e \"s/myuser/${POSTGRES_USER}/g\" /etc/postfix/conf.d/pgsql-transport-maps.cf.tpl > /etc/postfix/conf.d/pgsql-transport-maps.cf &&
      sed -i -e \"s/mypassword/$(echo ${POSTGRES_PASSWORD} | sed 's/[][\/\.|$(){}?+*^]/\\\\&/g')/g\" /etc/postfix/conf.d/pgsql-transport-maps.cf &&
      sed -i -e \"s/domain.tld/${DOMAIN}/g\" /etc/postfix/conf.d/pgsql-transport-maps.cf &&
      exec postfix start-fg"
