version: "3.8"

# Including necessary compose files for different services
include:
  - nginx-compose.yaml
  - simple-login-compose.yaml
  - postfix-compose.yaml

# Networks configuration
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
