version: "3.8"

services:
  ## NGINX & SSL CERTS
  ## =================

  nginx:
    image: nginx:1.25.2
    container_name: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./acme.sh/conf.d/:/etc/acme.sh/:ro
      - ./acme.sh/www/:/var/www/:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN:-app}
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /etc/nginx/conf.d/default.conf ]; then
        sed -e \"s/app.domain.tld/${SUBDOMAIN}.${DOMAIN}/g\" -e \"s/domain.tld/${DOMAIN}/g\" /etc/nginx/conf.d/default-init.conf.tpl > /etc/nginx/conf.d/default.conf;
      fi &&
      exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  acme.sh:
    image: private/acme.sh:latest
    build:
      context: ./acme.sh/Dockerfiles/
      dockerfile: Dockerfile
    container_name: acme.sh
    env_file: .env
    volumes:
      - ./acme.sh/www/:/var/www/:rw
      - ./acme.sh/conf.d/:/root/.acme.sh/:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx
